### ISSUE TITLE
Could not locate Gemfile

### ISSUE THREAD

**Issue by devilmind** [Grafeas/grafeas.github.io#26]
Hi All,
I'm in that foder:
**home/user/github/grafeas.github.io**
in that folder there are all git files downloaded, gemfile included but when I triggering the command:

`docker run --name grafeas-jekyll --volume=$(pwd):/srv/jekyll  -it -p 127.0.0.1:4000:4000 jekyll/jekyll:3.5.2 sh -c "bundle install && rake test && jekyll serve"`

I'm obtaining:
**Could not locate Gemfile**

and the container exiting continously....
can you help me pls?

Thank you

**Comment by devilmind81** [comment]
closes #26

**Comment by devilmind81** [comment]
I'm using the docker on WSL so the path of docker executable was different from the path were I issue the command. This was the issue.
This issue can be closed, sorry.

**Comment by aysylu** [comment]
Thanks for updating! I'll close the issue. Out of curiosity, may I ask why you're trying to bring up the local copy of the website and what you'd like to do with it?

**Comment by devilmind81** [comment]
Hi @aysylu ,
my target is to create a local Grafeas website "dockerized" in order to test the API and all functionalities to understand if I can use it in my devops pipelines. but till now I cannot able to do it. I'm obtaining an  issues during the build described here( https://github.com/grafeas/grafeas.github.io/issues/27 ).
Do you know if already exists a docker image for that scope? Otherwise....ho can test the api in other way? 
Thanks a lot for the infos

**Comment by aysylu** [comment]
@devilmind81: yes, there's a Docker file in github.com/grafeas/grafeas. Perhaps you meant to leave feedback/comments in that project? This one is for the grafeas.io website specifically.
